name = "DashBase"
uuid = "03207cf0-e2b3-4b91-9ca8-690cf0fb507e"
authors = ["Alexandr Romanenko <waralex@gmail.com>"]
version = "0.2.0"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
DashBasePlotsExt = "Plots"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
JSON3 = "1"
julia = "1.9"
Plots = "1"

[targets]
test = ["Test"]
