name = "DashBase"
uuid = "03207cf0-e2b3-4b91-9ca8-690cf0fb507e"
authors = ["Alexandr Romanenko <waralex@gmail.com>"]
version = "0.1.0"

[deps]
JSON2 = "2535ab7d-5cd8-5a07-80ac-9b1792aadce3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"


[compat]
JSON2 = "0.3.1"
julia = "1.2"
